# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Bruno Pires
description: "A free Jekyll theme for download"
keywords: "software, dev, developer, engineer, ios, web, bruno, pires"
url: http://brunopires.pt
baseurl: ""

#google_analytics: UA-52446115-1
#repo: http://github.com/nandomoreirame/end2end
#disqus_shortname: "nandothemes"
#disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Bruno Pires
  job: Software Engineer
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb: /images/author.jpg
  email: bruno@blastersystems.com
  url: http://brunopires.pt/
  github: https://github.com/piresbruno
  twitter: https://twitter.com/brunoacpires
  #facebook: https://facebook.com/umdevux
  #linkedin: https://linkedin.com/in/nandomoreirame

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
